server:
  port: 7654

spring.application.name: observabilityserver
  
  # All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  otlp:
    metrics:
      export:
        url: https://localhost:4318/v1/metrics